trigger:
  branches:
    include:
      - main
      - master
      - release/*
      - refs/tags/R*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Checkout@1
    displayName: 'Checkout code from GitHub'

  - script: echo "Triggered on $(Build.SourceBranch)"
    displayName: 'Print Trigger Info'

  - script: |
      echo "Building the project..."
      # Add your build commands here
    displayName: 'Build Step'

  - script: |
      echo "Running tests..."
      # Add your test commands here
    displayName: 'Test Step'
