trigger:
  branches:
    include:
      - main
      - master
      - release/*

pr:
  branches:
    include:
      - main
      - master
      - release/*

# Tag trigger using pipeline resources
resources:
  repositories:
    - repository: self
      type: github
      ref: refs/tags/R*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Checkout@1
    displayName: 'Checkout code from GitHub'

  - script: echo "Triggered from branch or tag: $(Build.SourceBranch)"
    displayName: 'Show Trigger Info'

  - script: |
      echo "Building the project..."
      # Add your build commands here
    displayName: 'Build Step'

  - script: |
      echo "Running tests..."
      # Add your test commands here
    displayName: 'Test Step'
